title: 标题
description: 你的描述
url: https://Physics-ZheLI.github.io
baseurl: ""              # 根站点建议留空
timezone: Asia/Singapore # 或 Asia/Shanghai

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # 可选再加：
  # - jekyll-sitemap

# 导航里显示哪些页面（minima）
header_pages:
  - index.md
  - about.md

# 社交链接（minima 支持）
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/Physics-ZheLI" }
