title: "精神と時の部屋"
description: "A personal site powered by Minimal Mistakes"
url: "https://physics-zheli.github.io"
baseurl: ""
theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  hard_wrap: false
  
# 基础信息
author:
  name: "Zhe Li"
  avatar: "/assets/images/me.jpg"  # 你的头像路径
  bio: "Physics Master Student | Exploring math, physics, and code"
  location: "Shanghai, China"

# 社交媒体
social:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Physics-ZheLi"

# 导航菜单
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Posts"
    url: /posts/
